name: Publish to Registry
on:
    schedule:
        - cron: '0 17 * * 1' # Monday at 10am PDT
    release:
        types: [published]
    push:
        branches:
            - master
    pull_request: # Only for testing, remove before land
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              pre: >
                  echo ::save-state name=RELEASE_VERSION::$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')
              with:
                  name: querybook/querybook
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  tags: 'latest,${{ env.STATE_RELEASE_VERSION }}'
