# Public Configs are shared between backend and frontend and are not sensitive
# --------------- AI Assistant ---------------
ai_assistant:
    enabled: false

    query_title_generation:
        enabled: true

    query_generation:
        enabled: true

    query_auto_fix:
        enabled: true

    table_vector_search:
        enabled: false

survey:
    global_response_cooldown: 2592000 # 30 days
    global_trigger_cooldown: 600 # 10 minutes
    global_max_per_week: 6
    global_max_per_day: 3

    # Please refer to the querybook guide on how to enable surveys
    surfaces: []
